service: screenshot
provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: production
  deploymentBucket:
    name: cq-screenshot-service-pr-serverlessdeploymentbuck-kkaocv7d3u87

functions:
  screenshot:
    handler: handler.screenshot
    timeout: 30
    events:
      - http:
          path: screenshot
          method: get
          contentHandling: CONVERT_TO_BINARY
    environment:
      HOME: /var/task

plugins:
  - serverless-apigwy-binary
  - serverless-apigw-binary

custom:
  apigwBinary:
    types:
      - "*/*"
